/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Inquiry = IDL.Record({
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const LoginResult = IDL.Record({
  'success' : IDL.Bool,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  'clearAllInquiries' : IDL.Func([], [], []),
  'clearAllUsers' : IDL.Func([], [], []),
  'forgotPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'isEmailRegistered' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'loginUser' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], ['query']),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Inquiry = IDL.Record({
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const LoginResult = IDL.Record({
    'success' : IDL.Bool,
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    'clearAllInquiries' : IDL.Func([], [], []),
    'clearAllUsers' : IDL.Func([], [], []),
    'forgotPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'isEmailRegistered' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'loginUser' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], ['query']),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
    'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
